version: '3.8'

services:
  mongo:
    image: mongodb/mongodb-community-server
    container_name: monguito
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb/data:/data/db
